# Generated by Django 4.1.5 on 2023-02-04 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="zip",
            new_name="zipcode",
        ),
    ]
