# Generated by Django 4.1.5 on 2023-02-06 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopapp", "0004_rename_zip_customer_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=models.IntegerField(default=91),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(
                choices=[
                    ("Andaman and Nicobar Island", "Andaman and Nicobar Island"),
                    ("Andra pradesh", "Andra pradesh"),
                    ("Assam", "Assam"),
                    ("Bihar", "Bihar"),
                    ("Kerala", "Kerala"),
                    ("Delhi", "Delhi"),
                    ("Goa", "Goa"),
                    ("Hariyana", "Hariyana"),
                    ("Punjab", "Punjab"),
                    ("Rajasthan", "Rajasthan"),
                    ("Tamilnadu", "Tamilnadu"),
                    ("Karnataka", "Karnataka"),
                    ("WestBengal", "WestBengal"),
                    ("Uttarpradesh", "Uttarpradesh"),
                    ("Madhyapradesh", "Madhyapradesh"),
                    ("Gujarat", "Gujarat"),
                    ("Meghalaya", "Meghalaya"),
                    ("Mizoram", "Mizoram"),
                    ("Odisa", "Odisa"),
                    ("Nagaland", "Nagaland"),
                    ("Sikkim", "Sikkim"),
                    ("Uttarakhand", "Uttarakhand"),
                    ("Arunachalpradesh", "Arunachalpradesh"),
                    ("Jammukashmir", "Jammukashmir"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "products",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shopapp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
