# Generated by Django 4.1.5 on 2023-02-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_alter_customer_mobile_alter_customer_state_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="products",
            new_name="product",
        ),
    ]
