# Generated by Django 4.1.5 on 2023-02-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_payment_orderplaced"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderplaced",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="orderplaced",
            name="payment",
        ),
    ]
